---
all:
  children:
    # Parent group containing all ProxMox related hosts (hypervisors and VMs)
    # This allows group_vars/proxmox.yml variables to load automatically for both
    proxmox:
      children:
        proxmox_hypervisors:
          hosts:
            pve-01.example.com:
              ansible_host: 192.168.1.10
            pve-02.example.com:
              ansible_host: 192.168.1.11

        vms:
          children:
            gitlab_servers:
              hosts:
                gitlab-vm.example.com:
                  ansible_host: 192.168.1.50
                  vmid: 150
                  pve_node: "pve-01"
                  pve_hypervisor_host: "pve-01.example.com"
                  vm_cores: 2
                  vm_ram: 4096
                  vm_disk_size: "50G"
                  vm_prefix: 24
                  vm_gateway: "192.168.1.1"

            zabbix_servers:
              hosts:
                zabbix-vm.example.com:
                  ansible_host: 192.168.1.60
                  vmid: 160
                  pve_node: "pve-02"
                  pve_hypervisor_host: "pve-02.example.com"
                  vm_cores: 2
                  vm_ram: 2048
                  vm_disk_size: "20G"
                  vm_prefix: 24
                  vm_gateway: "192.168.1.1"

            app_servers:
              hosts:
                app-vm-01.example.com:
                  ansible_host: 192.168.1.71
                  vmid: 171
                  pve_node: "pve-01"
                  pve_hypervisor_host: "pve-01.example.com"
                  vm_cores: 1
                  vm_ram: 1024
                  vm_disk_size: "10G"
                  vm_prefix: 24
                  vm_gateway: "192.168.1.1"
                app-vm-02.example.com:
                  ansible_host: 192.168.1.72
                  vmid: 172
                  pve_node: "pve-02"
                  pve_hypervisor_host: "pve-02.example.com"
                  vm_cores: 1
                  vm_ram: 1024
                  vm_disk_size: "10G"
                  vm_prefix: 24
                  vm_gateway: "192.168.1.1"

    # Group containing all nodes that need to run Zabbix Agent and be monitored
    monitored_nodes:
      children:
        gitlab_servers:
        zabbix_servers:
        app_servers:
...
