---
- name: Clone virtual machine from template
  community.proxmox.proxmox_kvm: &pve_kvm_default
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    node: "{{ pve_node }}"
    vmid: "{{ vmid }}"
    name: "{{ inventory_hostname.split('.')[0] }}"
    clone: "{{ pve_template }}"
    timeout: 300
    state: present
  delegate_to: "{{ pve_hypervisor_host }}"
  tags:
    - vm_clone
    - provision

- name: Configure virtual machine hardware settings
  community.proxmox.proxmox_kvm:
    <<: *pve_kvm_default
    cores: "{{ vm_cores | default(pve_vm_cores) }}"
    memory: "{{ vm_ram | default(pve_vm_ram) }}"
    update: true
  delegate_to: "{{ pve_hypervisor_host }}"
  tags:
    - vm_config
    - provision

- name: Configure VM cloud-init networking
  community.proxmox.proxmox_kvm:
    <<: *pve_kvm_default
    ipconfig:
      ipconfig0: "ip={{ ansible_host }}/{{ vm_prefix | default(24) }},gw={{ vm_gateway }}"
    update: true
  delegate_to: "{{ pve_hypervisor_host }}"
  tags:
    - vm_network
    - provision

- name: Ensure virtual machines are started
  community.proxmox.proxmox_kvm:
    <<: *pve_kvm_default
    state: started
  delegate_to: "{{ pve_hypervisor_host }}"
  tags:
    - vm_start
    - provision
...
